require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PecasController do

  # This should return the minimal set of attributes required to create a valid
  # Peca. As you add validations to Peca, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PecasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pecas as @pecas" do
      peca = Peca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pecas).should eq([peca])
    end
  end

  describe "GET show" do
    it "assigns the requested peca as @peca" do
      peca = Peca.create! valid_attributes
      get :show, {:id => peca.to_param}, valid_session
      assigns(:peca).should eq(peca)
    end
  end

  describe "GET new" do
    it "assigns a new peca as @peca" do
      get :new, {}, valid_session
      assigns(:peca).should be_a_new(Peca)
    end
  end

  describe "GET edit" do
    it "assigns the requested peca as @peca" do
      peca = Peca.create! valid_attributes
      get :edit, {:id => peca.to_param}, valid_session
      assigns(:peca).should eq(peca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Peca" do
        expect {
          post :create, {:peca => valid_attributes}, valid_session
        }.to change(Peca, :count).by(1)
      end

      it "assigns a newly created peca as @peca" do
        post :create, {:peca => valid_attributes}, valid_session
        assigns(:peca).should be_a(Peca)
        assigns(:peca).should be_persisted
      end

      it "redirects to the created peca" do
        post :create, {:peca => valid_attributes}, valid_session
        response.should redirect_to(Peca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved peca as @peca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peca.any_instance.stub(:save).and_return(false)
        post :create, {:peca => {}}, valid_session
        assigns(:peca).should be_a_new(Peca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peca.any_instance.stub(:save).and_return(false)
        post :create, {:peca => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested peca" do
        peca = Peca.create! valid_attributes
        # Assuming there are no other pecas in the database, this
        # specifies that the Peca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Peca.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => peca.to_param, :peca => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested peca as @peca" do
        peca = Peca.create! valid_attributes
        put :update, {:id => peca.to_param, :peca => valid_attributes}, valid_session
        assigns(:peca).should eq(peca)
      end

      it "redirects to the peca" do
        peca = Peca.create! valid_attributes
        put :update, {:id => peca.to_param, :peca => valid_attributes}, valid_session
        response.should redirect_to(peca)
      end
    end

    describe "with invalid params" do
      it "assigns the peca as @peca" do
        peca = Peca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peca.any_instance.stub(:save).and_return(false)
        put :update, {:id => peca.to_param, :peca => {}}, valid_session
        assigns(:peca).should eq(peca)
      end

      it "re-renders the 'edit' template" do
        peca = Peca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peca.any_instance.stub(:save).and_return(false)
        put :update, {:id => peca.to_param, :peca => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested peca" do
      peca = Peca.create! valid_attributes
      expect {
        delete :destroy, {:id => peca.to_param}, valid_session
      }.to change(Peca, :count).by(-1)
    end

    it "redirects to the pecas list" do
      peca = Peca.create! valid_attributes
      delete :destroy, {:id => peca.to_param}, valid_session
      response.should redirect_to(pecas_url)
    end
  end

end
